server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
app:
  client-list-page:
    msg: Сегодня прекрасный день!!!
    msg2: ${app.client-list-page.msg} Завтра будет еще лучше!
